#!/bin/bash

rm build/*

echo "Synthesize design..."
yosys  -q -p "synth_ecp5 -top blinky -json build/blinky.json -noccu2 -nomux -nodram" blinky.v

echo "Place and Route..."
nextpnr-ecp5 --85k --package CABGA381 --json build/blinky.json --lpf ulx3s_v20.lpf --textcfg build/blinky.config --ignore-loops

echo "Create Bitstream..."
ecppack --input build/blinky.config --bit blinky.bit

echo "Finished."
