#!/bin/bash

echo "-------------------------------------------------------------------------------"
echo "  Compile Ice Cream Machine..."
echo "-------------------------------------------------------------------------------"

cd common-crosscompiler
fpc -XX -O3 icecreammachine-8kb.pas
fpc -XX -O3 icecreammachine-16kb.pas
rm *.o
cd ..

echo "-------------------------------------------------------------------------------"
echo "  Testsuite"
echo "-------------------------------------------------------------------------------"

cd testsuite
mkdir build
./compilenucleus
./testing
cd ..

echo "-------------------------------------------------------------------------------"
echo "COMPILING FOR PICO-ICE"
echo "-------------------------------------------------------------------------------"

cd pico-ice
./compile

