#!/bin/bash

echo "-------------------------------------------------------------------------------"
echo "  Compile Ice Cream Machine..."
echo "-------------------------------------------------------------------------------"

cd common-crosscompiler
fpc -XX -O3 icecreammachine-8kb.pas
fpc -XX -O3 icecreammachine-16kb.pas
rm *.o
cd ..

echo "-------------------------------------------------------------------------------"
echo "  Testsuite"
echo "-------------------------------------------------------------------------------"

cd testsuite
./testing
cd ..

echo "NOW CHANGE INTO YOUR TARGET BOARD DIRECTORY AND TYPE ./compile""
