#!/bin/bash

./compilenucleus

echo "Synthesize design..."
yosys  -q -p "synth_ecp5 -top top -json build/j1a.json -noccu2 -nomux -nodram" trellis/j1a.v

echo "Place and Route..."
nextpnr-ecp5 --85k --package CABGA381 --json build/j1a.json --lpf trellis/ulx3s_v20.lpf --textcfg build/j1a.config --ignore-loops

echo "Create Bitstream..."
ecppack --input build/j1a.config --bit j1a.bit

echo "Finished."
