#!/bin/sh

echo "Synthesize design..."
yosys  -q -p "synth_ice40 -top top -json build/hello.json -blif build/hello.blif -dsp -relut -abc2" hello.v

echo "Place and Route..."
nextpnr-ice40 --freq 24 --up5k --package sg48 --asc build/hello.txt --pcf icebreaker.pcf --json build/hello.json --ignore-loops --pcf-allow-unconstrained

echo "Create Bitstream..."
icepack build/hello.txt build/hello0.bin
icemulti -p0 build/hello0.bin > hello.bin

echo "Finished."
