#!/bin/bash

echo "Tidy up..."
rm -f build/*

echo "Compile nucleus..."
cp ../common-crosscompiler/cross-8kb.fs cross.fs
cp ../common-crosscompiler/instructionset-8kb.fs instructionset.fs
gforth cross.fs instructionset.fs nucleus.fs
rm cross.fs instructionset.fs
echo ""

echo "Compile additional Forth sources..."
cat ../common-forth/coredefinitions.fs basisdefinitions.fs ../common-forth/insight-8kb.fs > included.fs
../common-crosscompiler/icecreammachine-8kb build/nucleus.hex build/iceimage.hex included.fs > build/log.txt

md5sum build/nucleus.hex build/iceimage.hex
