#!/bin/bash

rm -f ex1
rm -f out.vcd

iverilog -g2005-sv  -Wall -s tb -o ex1  testspi.v 
if [ $? -eq 1 ]; then
    echo Source compilation failure
    exit 1
fi

vvp ex1  | more 

if [ $? -ne 0 ]; then
    echo Running simulation failure
    exit 1
fi

#gtkwave signal.gtkw 
if [$? -ne 0]; then
    echo GTKWave failure
    exit 1
fi

