#!/bin/bash

./compilenucleus

echo "Synthesize design..."
yosys  -q -p "synth_ice40 -top top -json build/j1a.json -blif build/j1a.blif" icestorm/j1a.v

echo "Place and Route..."
# arachne-pnr -p icestorm/j1a.pcf build/j1a.blif -o build/j1a.txt -d 8k -P tq144:4k
nextpnr-ice40 --freq 36 --hx8k --package tq144:4k --asc build/j1a.txt --pcf icestorm/j1a.pcf --json build/j1a.json --ignore-loops --pcf-allow-unconstrained

echo "Create Bitstream..."
icepack build/j1a.txt j1a0.bin

echo "Finished."
